#!/bin/sh

set -e

if [ "$1" = "configure" ] ; then
	update-alternatives --install /usr/bin/ostestr ostestr /usr/bin/python3-ostestr 200
	update-alternatives --install /usr/bin/subunit-trace subunit-trace /usr/bin/python3-subunit-trace 200
	update-alternatives --install /usr/bin/subunit2html subunit2html /usr/bin/python3-subunit2html 200
	update-alternatives --install /usr/bin/generate-subunit generate-subunit /usr/bin/python3-generate-subunit 200
fi

#DEBHELPER#

exit 0
